apiVersion: v1
kind: Secret
metadata:
  name: crapi-workshop-secret
  labels:
    app: crapi-workshop
type: Opaque
stringData:
  SECRET_KEY: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
  MONGO_DB_PASSWORD: CHANGE_ME
