apiVersion: v1
kind: Secret
metadata:
  name: crapi-chatbot-secret
  labels:
    app: crapi-chatbot
type: Opaque
stringData:
  DB_PASSWORD: CHANGE_ME
  MONGO_DB_PASSWORD: CHANGE_ME
  API_PASSWORD: CHANGE_ME
