name: APIShield DevSecOps
 
on:
  push:
    branches:
      - main
      - member*
 
  pull_request:
    branches:
      - main
 
jobs:
 
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Validate Structure
        run: |
          test -d docs
          test -d evidence
 
  semgrep:
    name: SAST
    needs: validate
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Run Semgrep
        run: |
          docker run --rm \
          -v "$GITHUB_WORKSPACE:/src" \
          semgrep/semgrep \
          semgrep scan \
          --config auto \
          /src
 
 
